"use client";

import { useMemo, useState } from "react";
import { signIn, useSession } from "next-auth/react";
import LoaderOverlay from "@/components/LoaderOverlay";
import ResultOverlay from "@/components/ResultOverlay";
import { Card } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import {
  generateShiftEvents,
  type ShiftConfig,
  type ShiftEvent,
} from "@/lib/generator";

const todayISO = new Date().toISOString().slice(0, 10);
const CHUNK_SIZE = 25;

export default function Page() {
  const { status } = useSession(); // "authenticated" | "unauthenticated" | "loading"

  const [cfg, setCfg] = useState<ShiftConfig>({
    timezone: process.env.NEXT_PUBLIC_DEFAULT_TZ || "Europe/London",
    rangeStart: todayISO,
    rangeEnd: new Date(new Date().setMonth(new Date().getMonth() + 11))
      .toISOString()
      .slice(0, 10),
    anchorOnDate: todayISO,
    startMode: "day",
    rotationWeeks: 2,
    dayStart: "07:25",
    nightStart: "19:25",
    hoursPerShift: 12,
    dayTitle: "Day Shift",
    nightTitle: "Night Shift",
    description: "Generated by ND Shift Rota",
    location: "Magna",
    lockTypePerCluster: true,
    rotationMode: "twoBlock",
  });

  const [useDedicated, setUseDedicated] = useState(true);
  const [dedicatedName, setDedicatedName] = useState("Shift Rota");
  const [dedicatedColorId, setDedicatedColorId] = useState("11");

  const [isPushing, setIsPushing] = useState(false);
  const [result, setResult] = useState<null | {
    ok: boolean;
    title: string;
    sub?: string;
  }>(null);
  const [progress, setProgress] = useState<{
    current: number;
    total: number;
  } | null>(null);

  const events = useMemo<ShiftEvent[]>(() => generateShiftEvents(cfg), [cfg]);

  function chunk<T>(arr: T[], size: number) {
    const out: T[][] = [];
    for (let i = 0; i < arr.length; i += size) out.push(arr.slice(i, i + size));
    return out;
  }

  async function pushToGoogle() {
    console.log("pushToGoogle called, status:", status);
    if (status !== "authenticated") {
      console.log("Not authenticated, redirecting to sign in");
      await signIn("google", { callbackUrl: window.location.href });
      return;
    }
    console.log("Authenticated, starting push process");
    setIsPushing(true);
    setResult(null);
    setProgress({ current: 0, total: events.length });

    let totalUpserted = 0;

    try {
      const batches = chunk(events, CHUNK_SIZE);
      console.log("Created", batches.length, "batches");
      for (const part of batches) {
        console.log("Making request for batch with", part.length, "events");
        console.log("About to make fetch request to /api/push");
        const res = await fetch("/api/push", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            events: part,
            timezone: cfg.timezone,
            useDedicatedCalendar: useDedicated,
            dedicatedCalendarName: dedicatedName,
            dedicatedCalendarColorId: dedicatedColorId,
          }),
        });
        console.log("Fetch response received:", res.status, res.statusText);

        if (res.status === 401) {
          await signIn("google", { callbackUrl: window.location.href });
          return;
        }

        const raw = await res.text();
        let parsed: any = null;
        try {
          parsed = JSON.parse(raw);
        } catch {}

        if (!res.ok) {
          const msg = parsed
            ? parsed.message || raw || res.statusText
            : raw || res.statusText;
          setResult({
            ok: false,
            title: "Failed to update calendar",
            sub: String(msg),
          });
          return;
        }

        const up = Number(parsed?.upserted ?? part.length);
        totalUpserted += up;

        setProgress((prev) =>
          prev
            ? {
                current: Math.min(prev.current + up, prev.total),
                total: prev.total,
              }
            : null
        );
      }

      setResult({
        ok: true,
        title: "Calendar updated!",
        sub: `Synced ${totalUpserted} events to ${
          useDedicated ? dedicatedName : "primary"
        }`,
      });
    } catch (err: any) {
      setResult({
        ok: false,
        title: "Network error",
        sub: err?.message || String(err),
      });
    } finally {
      setIsPushing(false);
      setProgress(null);
    }
  }

  const qs = new URLSearchParams({
    tz: cfg.timezone,
    rs: cfg.rangeStart,
    re: cfg.rangeEnd,
    anchor: cfg.anchorOnDate,
    mode: cfg.startMode,
    rotw: String(cfg.rotationWeeks),
    dstart: cfg.dayStart,
    nstart: cfg.nightStart,
    hours: String(cfg.hoursPerShift),
    dtitle: cfg.dayTitle || "",
    ntitle: cfg.nightTitle || "",
    desc: cfg.description || "",
    lock: cfg.lockTypePerCluster ? "1" : "0",
    rmode: cfg.rotationMode ?? "twoBlock",
  }).toString();

  async function deleteFromGoogle() {
    if (status !== "authenticated") {
      await signIn("google", { callbackUrl: window.location.href });
      return;
    }
    setIsPushing(true);
    setResult(null);
    try {
      const res = await fetch("/api/delete", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          start: cfg.rangeStart,
          end: cfg.rangeEnd,
          useDedicatedCalendar: useDedicated,
          dedicatedCalendarName: dedicatedName,
        }),
      });

      if (res.status === 401) {
        await signIn("google", { callbackUrl: window.location.href });
        return;
      }

      const parsed = await res.json().catch(() => ({}));
      if (!res.ok) {
        setResult({
          ok: false,
          title: "Delete failed",
          sub: parsed?.message || res.statusText,
        });
        return;
      }
      setResult({
        ok: true,
        title: "Deleted",
        sub: `Removed ${parsed.deleted} events from ${parsed.calendarId}`,
      });
    } catch (err: any) {
      setResult({
        ok: false,
        title: "Network error",
        sub: err?.message || String(err),
      });
    } finally {
      setIsPushing(false);
    }
  }

  return (
    <div className="container">
      <h1>4-on-4-off Shift Rota</h1>

      {/* gentle sign-in nudge */}
      {status !== "authenticated" && (
        <Card padding="md" elevation="md">
          <p style={{ marginBottom: 'var(--space-md)' }}>
            <strong>Sign in to sync with Google Calendar.</strong>
          </p>
          <div style={{ display: 'flex', gap: 'var(--space-md)', flexWrap: 'wrap' }}>
            <Button variant="primary" onClick={() => signIn("google", { callbackUrl: window.location.href })}>
              Sign in with Google
            </Button>
            <Button variant="secondary" asChild>
              <a href="/auth/request">Not on the tester list? Request access</a>
            </Button>
          </div>
        </Card>
      )}

      <Card padding="lg" elevation="md">
        <div style={{ 
          display: 'grid', 
          gap: 'var(--space-md)',
          gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))'
        }}>
          <div>
            <label style={{ display: 'block', marginBottom: 'var(--space-xs)', fontWeight: 500 }}>Timezone</label>
            <input
              type="text"
              value={cfg.timezone}
              onChange={(e) => setCfg({ ...cfg, timezone: e.target.value })}
              style={{
                width: '100%',
                padding: 'var(--space-sm)',
                border: '1px solid var(--color-border)',
                borderRadius: 'var(--radius-md)',
                backgroundColor: 'var(--color-surface)',
                color: 'var(--color-text)',
                fontSize: 'var(--font-size-sm)'
              }}
            />
          </div>
          <div>
            <label style={{ display: 'block', marginBottom: 'var(--space-xs)', fontWeight: 500 }}>Season Start</label>
            <input
              type="date"
              value={cfg.rangeStart}
              onChange={(e) => setCfg({ ...cfg, rangeStart: e.target.value })}
              style={{
                width: '100%',
                padding: 'var(--space-sm)',
                border: '1px solid var(--color-border)',
                borderRadius: 'var(--radius-md)',
                backgroundColor: 'var(--color-surface)',
                color: 'var(--color-text)',
                fontSize: 'var(--font-size-sm)'
              }}
            />
          </div>
          <div>
            <label style={{ display: 'block', marginBottom: 'var(--space-xs)', fontWeight: 500 }}>Season End</label>
            <input
              type="date"
              value={cfg.rangeEnd}
              onChange={(e) => setCfg({ ...cfg, rangeEnd: e.target.value })}
              style={{
                width: '100%',
                padding: 'var(--space-sm)',
                border: '1px solid var(--color-border)',
                borderRadius: 'var(--radius-md)',
                backgroundColor: 'var(--color-surface)',
                color: 'var(--color-text)',
                fontSize: 'var(--font-size-sm)'
              }}
            />
          </div>
          <div>
            <label style={{ display: 'block', marginBottom: 'var(--space-xs)', fontWeight: 500 }}>Anchor ON Day (first of a 4-on block)</label>
            <input
              type="date"
              value={cfg.anchorOnDate}
              onChange={(e) => setCfg({ ...cfg, anchorOnDate: e.target.value })}
              style={{
                width: '100%',
                padding: 'var(--space-sm)',
                border: '1px solid var(--color-border)',
                borderRadius: 'var(--radius-md)',
                backgroundColor: 'var(--color-surface)',
                color: 'var(--color-text)',
                fontSize: 'var(--font-size-sm)'
              }}
            />
          </div>
          <div>
            <label style={{ display: 'block', marginBottom: 'var(--space-xs)', fontWeight: 500 }}>Rotation starts as</label>
            <select
              value={cfg.startMode}
              onChange={(e) => setCfg({ ...cfg, startMode: e.target.value as any })}
              style={{
                width: '100%',
                padding: 'var(--space-sm)',
                border: '1px solid var(--color-border)',
                borderRadius: 'var(--radius-md)',
                backgroundColor: 'var(--color-surface)',
                color: 'var(--color-text)',
                fontSize: 'var(--font-size-sm)'
              }}
            >
              <option value="day">Day</option>
              <option value="night">Night</option>
            </select>
          </div>
          <div>
            <label style={{ display: 'block', marginBottom: 'var(--space-xs)', fontWeight: 500 }}>Rotation rule</label>
            <select
              value={cfg.rotationMode ?? "twoBlock"}
              onChange={(e) => setCfg({ ...cfg, rotationMode: e.target.value as any })}
              style={{
                width: '100%',
                padding: 'var(--space-sm)',
                border: '1px solid var(--color-border)',
                borderRadius: 'var(--radius-md)',
                backgroundColor: 'var(--color-surface)',
                color: 'var(--color-text)',
                fontSize: 'var(--font-size-sm)'
              }}
            >
              <option value="twoBlock">2× 4-on → flip (recommended)</option>
              <option value="fortnight">Flip every N weeks</option>
            </select>
          </div>
          <div>
            <label style={{ display: 'block', marginBottom: 'var(--space-xs)', fontWeight: 500 }}>Day shift starts</label>
            <input
              type="time"
              value={cfg.dayStart}
              onChange={(e) => setCfg({ ...cfg, dayStart: e.target.value })}
              style={{
                width: '100%',
                padding: 'var(--space-sm)',
                border: '1px solid var(--color-border)',
                borderRadius: 'var(--radius-md)',
                backgroundColor: 'var(--color-surface)',
                color: 'var(--color-text)',
                fontSize: 'var(--font-size-sm)'
              }}
            />
          </div>
          <div>
            <label style={{ display: 'block', marginBottom: 'var(--space-xs)', fontWeight: 500 }}>Night shift starts</label>
            <input
              type="time"
              value={cfg.nightStart}
              onChange={(e) => setCfg({ ...cfg, nightStart: e.target.value })}
              style={{
                width: '100%',
                padding: 'var(--space-sm)',
                border: '1px solid var(--color-border)',
                borderRadius: 'var(--radius-md)',
                backgroundColor: 'var(--color-surface)',
                color: 'var(--color-text)',
                fontSize: 'var(--font-size-sm)'
              }}
            />
          </div>
          <div>
            <label style={{ display: 'block', marginBottom: 'var(--space-xs)', fontWeight: 500 }}>Hours per shift</label>
            <input
              type="number"
              min={1}
              value={cfg.hoursPerShift}
              onChange={(e) => setCfg({ ...cfg, hoursPerShift: Number(e.target.value) })}
              style={{
                width: '100%',
                padding: 'var(--space-sm)',
                border: '1px solid var(--color-border)',
                borderRadius: 'var(--radius-md)',
                backgroundColor: 'var(--color-surface)',
                color: 'var(--color-text)',
                fontSize: 'var(--font-size-sm)'
              }}
            />
          </div>
          <div>
            <label style={{ display: 'block', marginBottom: 'var(--space-xs)', fontWeight: 500 }}>Day title</label>
            <input
              type="text"
              value={cfg.dayTitle}
              onChange={(e) => setCfg({ ...cfg, dayTitle: e.target.value })}
              style={{
                width: '100%',
                padding: 'var(--space-sm)',
                border: '1px solid var(--color-border)',
                borderRadius: 'var(--radius-md)',
                backgroundColor: 'var(--color-surface)',
                color: 'var(--color-text)',
                fontSize: 'var(--font-size-sm)'
              }}
            />
          </div>
          <div>
            <label style={{ display: 'block', marginBottom: 'var(--space-xs)', fontWeight: 500 }}>Night title</label>
            <input
              type="text"
              value={cfg.nightTitle}
              onChange={(e) => setCfg({ ...cfg, nightTitle: e.target.value })}
              style={{
                width: '100%',
                padding: 'var(--space-sm)',
                border: '1px solid var(--color-border)',
                borderRadius: 'var(--radius-md)',
                backgroundColor: 'var(--color-surface)',
                color: 'var(--color-text)',
                fontSize: 'var(--font-size-sm)'
              }}
            />
          </div>
          <div>
            <label style={{ display: 'block', marginBottom: 'var(--space-xs)', fontWeight: 500 }}>Location</label>
            <input
              type="text"
              value={cfg.location}
              onChange={(e) => setCfg({ ...cfg, location: e.target.value })}
              style={{
                width: '100%',
                padding: 'var(--space-sm)',
                border: '1px solid var(--color-border)',
                borderRadius: 'var(--radius-md)',
                backgroundColor: 'var(--color-surface)',
                color: 'var(--color-text)',
                fontSize: 'var(--font-size-sm)'
              }}
            />
          </div>
        </div>

        <div style={{
          backgroundColor: 'var(--color-surface-hover)',
          border: '1px solid var(--color-border)',
          borderRadius: 'var(--radius-lg)',
          padding: 'var(--space-md)',
          marginTop: 'var(--space-md)'
        }}>
          <div style={{
            display: "flex",
            gap: "var(--space-md)",
            alignItems: "center",
            flexWrap: "wrap",
          }}>
            <label style={{ display: "flex", alignItems: "center", gap: "var(--space-sm)" }}>
              <input
                type="checkbox"
                checked={cfg.lockTypePerCluster ?? true}
                onChange={(e) => setCfg({ ...cfg, lockTypePerCluster: e.target.checked })}
                style={{ width: '1rem', height: '1rem' }}
              />
              Lock Day/Night per 4-on (recommended)
            </label>

            <label style={{ display: "flex", alignItems: "center", gap: "var(--space-sm)" }}>
              <input
                type="checkbox"
                checked={useDedicated}
                onChange={(e) => setUseDedicated(e.target.checked)}
                style={{ width: '1rem', height: '1rem' }}
              />
              Use dedicated "Shift Rota" calendar
            </label>

            {useDedicated && (
              <>
                <label>
                  <span style={{ fontSize: 'var(--font-size-xs)', color: 'var(--color-text-secondary)', display: 'block', marginBottom: 'var(--space-xs)' }}>
                    Calendar name
                  </span>
                  <input
                    type="text"
                    value={dedicatedName}
                    onChange={(e) => setDedicatedName(e.target.value)}
                    style={{
                      padding: 'var(--space-xs) var(--space-sm)',
                      border: '1px solid var(--color-border)',
                      borderRadius: 'var(--radius-sm)',
                      backgroundColor: 'var(--color-surface)',
                      color: 'var(--color-text)',
                      fontSize: 'var(--font-size-sm)'
                    }}
                  />
                </label>
                <label>
                  <span style={{ fontSize: 'var(--font-size-xs)', color: 'var(--color-text-secondary)', display: 'block', marginBottom: 'var(--space-xs)' }}>
                    Color ID
                  </span>
                  <input
                    type="number"
                    value={dedicatedColorId}
                    onChange={(e) => setDedicatedColorId(e.target.value)}
                    style={{
                      padding: 'var(--space-xs) var(--space-sm)',
                      border: '1px solid var(--color-border)',
                      borderRadius: 'var(--radius-sm)',
                      backgroundColor: 'var(--color-surface)',
                      color: 'var(--color-text)',
                      fontSize: 'var(--font-size-sm)'
                    }}
                  />
                </label>
              </>
            )}
          </div>
        </div>

        <div style={{ display: 'flex', gap: 'var(--space-md)', flexWrap: 'wrap', marginTop: 'var(--space-md)' }}>
          <Button variant="primary" onClick={pushToGoogle} disabled={isPushing}>
            {isPushing ? "Syncing…" : "Add to Google Calendar"}
          </Button>

          <Button variant="secondary" asChild disabled={isPushing}>
            <a href={`/api/ics?${qs}`} rel="noreferrer" target="_blank">
              Get ICS feed (subscribe)
            </a>
          </Button>

          <Button variant="secondary" onClick={deleteFromGoogle} disabled={isPushing}>
            {isPushing ? "Working…" : "Delete season (Google)"}
          </Button>
        </div>
      </Card>

      <Card padding="lg" elevation="md">
        <h3 style={{ fontSize: 'var(--font-size-xl)', marginBottom: 'var(--space-sm)' }}>
          Preview ({events.length} shifts)
        </h3>
        <div style={{ overflowX: 'auto' }}>
          <table style={{
            width: '100%',
            borderCollapse: 'collapse',
            fontSize: 'var(--font-size-sm)'
          }}>
            <thead>
              <tr>
                <th style={{
                  textAlign: 'left',
                  fontSize: 'var(--font-size-xs)',
                  fontWeight: 600,
                  color: 'var(--color-text-secondary)',
                  paddingBottom: 'var(--space-sm)',
                  borderBottom: '1px solid var(--color-border)'
                }}>Start (local)</th>
                <th style={{
                  textAlign: 'left',
                  fontSize: 'var(--font-size-xs)',
                  fontWeight: 600,
                  color: 'var(--color-text-secondary)',
                  paddingBottom: 'var(--space-sm)',
                  borderBottom: '1px solid var(--color-border)'
                }}>End (local)</th>
                <th style={{
                  textAlign: 'left',
                  fontSize: 'var(--font-size-xs)',
                  fontWeight: 600,
                  color: 'var(--color-text-secondary)',
                  paddingBottom: 'var(--space-sm)',
                  borderBottom: '1px solid var(--color-border)'
                }}>Type</th>
                <th style={{
                  textAlign: 'left',
                  fontSize: 'var(--font-size-xs)',
                  fontWeight: 600,
                  color: 'var(--color-text-secondary)',
                  paddingBottom: 'var(--space-sm)',
                  borderBottom: '1px solid var(--color-border)'
                }}>Title</th>
              </tr>
            </thead>
            <tbody>
              {events.slice(0, 100).map((ev) => (
                <tr key={ev.id}>
                  <td style={{ padding: 'var(--space-sm) 0', borderBottom: '1px dashed var(--color-border)' }}>
                    {new Date(ev.localStart).toLocaleString()}
                  </td>
                  <td style={{ padding: 'var(--space-sm) 0', borderBottom: '1px dashed var(--color-border)' }}>
                    {new Date(ev.localEnd).toLocaleString()}
                  </td>
                  <td style={{ padding: 'var(--space-sm) 0', borderBottom: '1px dashed var(--color-border)' }}>
                    {ev.type}
                  </td>
                  <td style={{ padding: 'var(--space-sm) 0', borderBottom: '1px dashed var(--color-border)' }}>
                    {ev.title}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        {events.length > 100 && (
          <p style={{ color: 'var(--color-text-secondary)', marginTop: 'var(--space-sm)', fontSize: 'var(--font-size-sm)' }}>
            Showing first 100…
          </p>
        )}
      </Card>

      {/* Overlays */}
      {isPushing && (
        <LoaderOverlay
          title="Syncing to Google Calendar…"
          subtitle="Please keep this tab open."
        />
      )}
      {result && (
        <ResultOverlay
          ok={result.ok}
          title={result.title}
          sub={result.sub}
          onClose={() => setResult(null)}
          autoHideMs={2200}
        />
      )}
    </div>
  );
}
